### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by jo0ger** [cli-table/cli-table3#147] opened 2020-01-14 08:42 UTC
My code：
``` js
const table2 = new Table({style:{head:[],border:[]}});

table2.push(
  [{rowSpan:5,content:1},{rowSpan:3,content:1},{colSpan: 5, content: 1}],
  [{colSpan: 5, content: 1}],
  [1,1,1,1,1],
  [1,1,1,1,1,1],
  [1,1,1,1,1,1]
)

console.log(table2.toString())
```

output:
```
┌───┬───┬───────────────────┐
│ 1 │ 1 │ 1                 │
│   │   ├───────────────────┤
│   │   │ 1                 │
│   │   ├───├───┬───┬───┬───┬───┤
│   │   │ 1 │ 1 │ 1 │ 1 │ 1 │   │
│   ├───┼───┼───┼───┼───┼───┤
│   │ 1 │ 1 │ 1 │ 1 │ 1 │ 1 │
│   ├───┼───┼───┼───┼───┼───┤
│   │ 1 │ 1 │ 1 │ 1 │ 1 │ 1 │
└───┴───┴───┴───┴───┴───┴───┘
```

![image](https://user-images.githubusercontent.com/16385416/72327898-e9263b00-36ec-11ea-921a-07a640e500f6.png)

**Comment by speedytwenty** [comment] 2021-05-04 01:50
This is a duplicate of #128. I tried jo0ger's code with the fix from #187 and it seems to resolve the issue:

![Screen Shot 2021-05-03 at 7 46 41 PM](https://user-images.githubusercontent.com/260874/116952790-c3f26e80-ac48-11eb-9bcd-b57f32ecd875.png)

**Closed** 2021-05-05 22:47 UTC
Labels: duplicate
