### ISSUE TITLE
Failing unit test

### ISSUE THREAD

**Issue by titanabrian** [cli-table/cli-table3#196] opened 2020-12-04 17:36 UTC
I tried to clone the project and run test in my local. But I got several tests are failing.
Im using MacOs with zsh command line

![Screen Shot 2020-12-05 at 00 36 42](https://user-images.githubusercontent.com/33713672/101195404-f3994c80-3691-11eb-9cae-26ae4a215633.png)
![Screen Shot 2020-12-05 at 00 36 33](https://user-images.githubusercontent.com/33713672/101195392-ee3c0200-3691-11eb-8674-4ed6c611ce3f.png)

**Comment by speedytwenty** [comment] 2021-05-04 00:36
Spent some time debugging this and I was able to trace it to a difference in versions of the "colors" module between cli-table and cli-table3. 

It's a bit tricky to debug for a couple reasons:
1) The tests that are failing are tests that run against cli-table and cli-table3. The tests are failing with cli-table and NOT cli-table3.
2) The failing tests are specifically testing colors, and while jest tries to be helpful with highlighting the failures, it's difficult to actually see what's going on. _If the visual appearance of the difference were accurate, both values would appear identical._

If you run: `npm list colors` you will see something like:
```
├─┬ cli-table@0.3.6
│ └── colors@1.0.3
└── colors@1.4.0
```

When I run: `npm i colors@1.0.3 && npm test` the tests that utilize the colors module in their expected values pass while tests that have hard-coded colors in their expected value fail.

So it's clear that colors is likely producing two different outputs based on the versions, but the actual difference is invisible.

This failing test does not indicate a functional bug with cli-table3 (nor cli-table). I'm not exactly sure the best route to go about resolving this to get the tests passing again.

I tend to avoid modifying tests as much as possible, but it might make sense to mock colors and test that it was called as expected rather than comparing the output. Alternatively, it might make sense to remove the tests against cli-table altogether as it is testing external code which cli-table sufficiently covers in it's tests.

**Comment by speedytwenty** [comment] 2021-05-04 01:29
After a closer look, considering the CI builds are passing. I discovered that the tests pass when ran with the "--runInBand" flag. I think this must result in the later version of colors being used throughout the test but I can't tell for sure.

Try `npm test -- --runInBand`

**Comment by speedytwenty** [comment] 2022-03-30 00:25
![image](https://user-images.githubusercontent.com/260874/160722825-ad533369-b037-4dec-9849-20286af1bb22.png)

The failing tests are caused by differences in output produced by the (obscure) "colors" module(s). Yet somehow, they didn't fail _before_ with Travis, nor _now_ with Github Actions. But if you download master, before this is resolved, and run `yarn install && yarn test` the above test will fail.

To be clear, this existed before cli-table3 moved to `@colors/colors`...and all that fiasco. Any actual differences in colors output expected by the [cli-table3 "legacy" tests](https://github.com/cli-table/cli-table3/blob/master/test/verify-legacy-compatibility-test.js#L2) while testing [cli-table](https://github.com/Automattic/cli-table) will cause the tests to fail.

I attempted a solution for this in #196 and realized it was inadequate—despite preventing the failing errors—the `--runInBand` flag may have unobservable or superfluous consequences.
 
The appropriate solution will be to mock the color module(s) within the tests implicated. But from there, the question becomes which version(s) of cli-table is cli-table3 attempting to support?

**Closed** 2022-03-30 18:32 UTC
